NMake Makefiles: Use /utf-8
This avoids error C4819 due to unicode handling issues in the compiler,
which is often raised when attempting to build in East-Asian locales
(Chinese, Japanese and Korean).  Since Visual Studio 2017 is required to
build the C++17/master branch of atkmm, this is enabled for all builds.