NMake Makefiles: Use /utf-8 for MSVC 2015 and later
This will prevent error C4819 due to unicode handling issues in the
compiler, which can be raised when building on an East-Asian locale
(Chinese, Japanese and Korean).  This build flag, however, is provided
only in Visual Studio 2015 and later, so 2013 users cannot benefit from
this change.